### ISSUE TITLE
Tag version 0.17.0

### ISSUE THREAD

**Issue by hyyan** [BBj-Plugins/DWCJ#7]
tag new version after updating `bbj-plugin.json`

**Comment by kevinhagel** [comment]
Resolved.  created tag 0.1.7 and published a release

**Comment by hyyan** [comment]
@kevinhagel you have not updated bbj-plugin.json, if you dont , the new version wont appear in the plugins manager

**Comment by hyyan** [comment]
Plus the version should be  0.17.0

**Comment by kevinhagel** [comment]
can we delete the release?

**Comment by kevinhagel** [comment]
deleted 0.1.7 release, deleted the tag, deleted it from local too.
modified bbj-plugin.json, set version to 0.17.0
created tag 0.17.0

**Comment by kevinhagel** [comment]
{
  "name": "DWCJ Dynamic Web Client for Java",
  "description": "Develop for the DWC in Java",
  "version": "0.17.0",
  "author": "Stephan Wald",
  "licence": "MIT",
  "bbj_dependency": "23.00",
  "plugin_dependencies": [],
  "plugin_development_dependencies": []
}

**Comment by kevinhagel** [comment]
hmm, it looks llike a race condition.  I committed the json after removing the old stuff, but before I created the release

**Comment by hyyan** [comment]
You will need to update the JSON , commit , then create a new version.
